In [9]:
import numpy as np

#### Here, we are using three text files containing news-pieces about the Euro 2020 football tournament.

In [1]:
# Reading the text files
file1 = open(r"C:\Users\user\Documents\Data Science\IRT\Euro1.txt")
file2 = open(r"C:\Users\user\Documents\Data Science\IRT\Euro2.txt")
file3 = open(r"C:\Users\user\Documents\Data Science\IRT\Euro3.txt")

In [4]:
# Python file method readlines() reads until EOF using readline() and returns a list containing the lines.
x=file1.readlines()
y=file2.readlines()
z=file3.readlines()

In [5]:
docs=x+y+z
docs

["Harry Kane sent England into uncharted waters on Wednesday when he scored to propel England past Denmark into the Euro 2020 final. His effort from the rebound off his initially saved penalty in extra time to send his country into their first ever European Championship final. It was also England's first ever major tournament final after the 1966 World Cup final. Kane tied Gary Lineker's record for the most combined England goals at European Championships and World Cups, but his extra time winner against Denmark came with huge controversy. It was Raheem Sterling who initially won the penalty which sparked the controversy. Sterling dashed through Denmark's defence in the first half of extra time, twisting past a couple of defenders. However, he appeared to go down under a challenge from Joakim Maehle and the referee promptly pointed to the penalty spot. VAR, understandably, had a look at the incident and upheld the decision much to the furore of the Danish defenders. Kane promptly stepp

In [6]:
# Gather the set of all unique terms
unique_terms = {term for doc in docs for term in doc.split()}
unique_terms

{'(26′,',
 '(D1',
 '(D2',
 '(D5',
 '(EURO/World',
 '(Soviet',
 '(W11',
 '(W27',
 '(World',
 '(open',
 '-',
 '0-0',
 '1-0',
 '1-1',
 '10',
 '10.',
 '100',
 '105th',
 '10th',
 '11.',
 '114th',
 '11th',
 '12',
 '12.',
 '120',
 '13',
 '13.',
 '13th',
 '14',
 '15',
 '17',
 '1958',
 '1960,',
 '1966',
 '1968,',
 '1972',
 '1977.',
 '1980',
 '1980,',
 '1990',
 '1996.',
 '1997',
 '2-0',
 '2-1',
 '2.',
 '2000',
 '2004',
 '2004.',
 '2012).',
 '2012.',
 '2013',
 '2014',
 '2016',
 '2018',
 '2020',
 '2020,',
 '2020.',
 '23',
 '3',
 '3-0',
 '3.',
 '31st',
 '33',
 '33-match',
 '39th',
 '4',
 '4-2',
 '4.',
 '40m',
 '44th',
 '46',
 '5.',
 '52′)',
 '53th',
 '55',
 '55th',
 '6',
 '6.',
 '60th',
 '66th',
 '7.',
 '70',
 '79th',
 '8.',
 '86',
 '89th',
 '9.',
 '90',
 '91',
 '95th',
 'AS',
 'Against',
 'Alcantara',
 'Alf',
 'Alvaro',
 'Ampadu',
 'Arsenal',
 'Arsene',
 'August',
 'Austria',
 'Austria’s',
 'Barella',
 'Belgium',
 'Belgium.',
 'Belotti,',
 'Bernardeschi',
 'Bonucci,',
 'Both',
 'Bruyne',
 'C

## Term Document Matrix

In [7]:
# Construct a term-document matrix

doc_term_matrix = {}

for term in unique_terms:
    doc_term_matrix[term] = []
    
    for doc in docs:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

doc_term_matrix

{'on': [1, 1, 1],
 'Italy': [0, 1, 1],
 'right': [0, 0, 1],
 '1968,': [0, 1, 0],
 'The': [1, 1, 1],
 'trophy': [0, 1, 0],
 'where': [0, 0, 1],
 'flair': [0, 0, 1],
 'However': [1, 0, 1],
 'continues': [0, 0, 1],
 "Italy's": [0, 1, 0],
 'failure': [0, 0, 1],
 'beginning': [0, 1, 0],
 'not': [1, 0, 1],
 'EURO,': [0, 1, 0],
 'Southgate,': [0, 1, 0],
 '1990': [0, 1, 0],
 '1-0': [0, 1, 1],
 'create': [0, 0, 1],
 'victory': [0, 0, 1],
 'dominating': [0, 0, 1],
 '6.': [0, 1, 0],
 'country': [1, 0, 0],
 'grit': [0, 0, 1],
 'more': [0, 1, 1],
 'part.': [0, 0, 1],
 'defenders.': [1, 0, 0],
 'that': [1, 0, 1],
 'talent,': [0, 0, 1],
 'final': [1, 1, 1],
 'Italians': [0, 0, 1],
 '13': [0, 1, 1],
 'abilities': [0, 0, 1],
 'any': [1, 1, 1],
 'increase': [0, 0, 1],
 '3': [0, 1, 1],
 'stunner': [0, 0, 1],
 'great': [0, 0, 1],
 'combined': [1, 0, 0],
 'Wembley.': [0, 1, 0],
 'under': [1, 1, 1],
 'this': [0, 1, 0],
 'tied': [1, 0, 0],
 '(Soviet': [0, 1, 0],
 'is': [1, 1, 1],
 'experienced': [0, 0, 1],
 

In [10]:
# The query to find all documents containing "home" AND "Kane"AND "Italy" AND "penalty"
# Is just a bitwise AND:



docs_array = np.array(docs, dtype='object')

v1 = np.array(doc_term_matrix['Kane'])    
v2 = np.array(doc_term_matrix['penalty'])
v3 = np.array(doc_term_matrix['Italy'])
print(v1)
print(v2)
print(v3)
print('-------')
v = v1 & v2 & v3
print(v)

[1 0 1]
[1 0 1]
[0 1 1]
-------
[0 0 1]


In [11]:
# We can now get the matching documents from our corpus with the result. Here, the result is the third file.
[doc for doc in v * docs_array if doc]

['Italy’s road to redemption after their failure to qualify for the 2018 FIFA World Cup continues at the European Championships 2020. Roberto Mancini has turned the team around with injection of youth along with the experienced and has brought some flair to the squad apart from the gritty defence that they have been known for. Italy are currently on a 33-match unbeaten streak and have shown both their flair and grit in Euro 2020 by sprinting to victories and fighting to them as well. Here is Italy’s road to the final: Italy came in to the semi-final as slight favourites against Spain based on the form in the tournament. However, Spain dominated the possession and did not allow Italy’s midfield to have any control over the proceedings. Against the run of play, Italy scored first off a counter-attack with Federico Chiesa scored a fantastic goal in the 60th minute. However after incessant attacking, Spain equalised through Alvaro Morata. The scoreline remained 1-1 after 120 minutes 

In [12]:
# Bitwise OR to construct 'football' or 'goal' queries.

v1 = np.array(doc_term_matrix['football'])    
v2 = np.array(doc_term_matrix['goal'])

print(v1)
print(v2)
print('-------')
v = v1 | v2
print(v)

[0 0 1]
[1 1 1]
-------
[1 1 1]


In [13]:
# We can now get the matching documents from our corpus with the result. Here, terms like football or goal can easily be found in any football article. Hence, as we can see, all three files contain the result.
[doc for doc in v * docs_array if doc]

["Harry Kane sent England into uncharted waters on Wednesday when he scored to propel England past Denmark into the Euro 2020 final. His effort from the rebound off his initially saved penalty in extra time to send his country into their first ever European Championship final. It was also England's first ever major tournament final after the 1966 World Cup final. Kane tied Gary Lineker's record for the most combined England goals at European Championships and World Cups, but his extra time winner against Denmark came with huge controversy. It was Raheem Sterling who initially won the penalty which sparked the controversy. Sterling dashed through Denmark's defence in the first half of extra time, twisting past a couple of defenders. However, he appeared to go down under a challenge from Joakim Maehle and the referee promptly pointed to the penalty spot. VAR, understandably, had a look at the incident and upheld the decision much to the furore of the Danish defenders. Kane promptly stepp

## Inverted Matrix

In [14]:
# Construct an inverted index

inverted_index = {}

for i, doc in enumerate(docs):
    for term in doc.split():
        if term in inverted_index:
            inverted_index[term].add(i)
        else: inverted_index[term] = {i}

inverted_index

{'Harry': {0, 2},
 'Kane': {0},
 'sent': {0},
 'England': {0, 1},
 'into': {0, 2},
 'uncharted': {0},
 'waters': {0},
 'on': {0, 1, 2},
 'Wednesday': {0},
 'when': {0, 2},
 'he': {0},
 'scored': {0, 1, 2},
 'to': {0, 1, 2},
 'propel': {0},
 'past': {0},
 'Denmark': {0, 1},
 'the': {0, 1, 2},
 'Euro': {0, 2},
 '2020': {0, 1, 2},
 'final.': {0},
 'His': {0},
 'effort': {0},
 'from': {0, 1, 2},
 'rebound': {0},
 'off': {0, 2},
 'his': {0},
 'initially': {0},
 'saved': {0},
 'penalty': {0, 2},
 'in': {0, 1, 2},
 'extra': {0, 1, 2},
 'time': {0, 2},
 'send': {0},
 'country': {0},
 'their': {0, 1, 2},
 'first': {0, 1, 2},
 'ever': {0, 1},
 'European': {0, 1, 2},
 'Championship': {0, 1},
 'It': {0},
 'was': {0, 1, 2},
 'also': {0, 1},
 "England's": {0, 1},
 'major': {0, 1},
 'tournament': {0, 1},
 'final': {0, 1, 2},
 'after': {0, 2},
 '1966': {0, 1},
 'World': {0, 1, 2},
 'Cup': {0, 1, 2},
 'tied': {0},
 'Gary': {0},
 "Lineker's": {0},
 'record': {0},
 'for': {0, 1, 2},
 'most': {0, 2},
 'co

In [16]:
# Now we can search for any term
posting_list = inverted_index['Euro']
posting_list

{0, 2}

We can define functions to find our required terms across the documents for OR condition and AND condition

In [17]:
def or_postings(posting1, posting2):
    p1 = 0
    p2 = 0
    result = list()
    while p1 < len(posting1) and p2 < len(posting2):
        if posting1[p1] == posting2[p2]:
            result.append(posting1[p1])
            p1 += 1
            p2 += 1
        elif posting1[p1] > posting2[p2]:
            result.append(posting2[p2])
            p2 += 1
        else:
            result.append(posting1[p1])
            p1 += 1
    while p1 < len(posting1):
        result.append(posting1[p1])
        p1 += 1
    while p2 < len(posting2):
        result.append(posting2[p2])
        p2 += 1
    return result

In [18]:
pl_1 = list(inverted_index['football'])
pl_2 = list(inverted_index['final'])
or_postings(pl_1, pl_2)

[0, 1, 2]

The terms 'football' OR 'final' exists in all three files.

In [19]:
def and_postings(posting1, posting2):
    p1 = 0
    p2 = 0
    result = list()
    while p1 < len(posting1) and p2 < len(posting2):
        if posting1[p1] == posting2[p2]:
            result.append(posting1[p1])
            p1 += 1
            p2 += 1
        elif posting1[p1] > posting2[p2]:
            p2 += 1
        else:
            p1 += 1
    return result

In [20]:
pl_1 = list(inverted_index['Kane'])
pl_2 = list(inverted_index['scored'])
and_postings(pl_1, pl_2)

[0]

The terms 'Kane' AND 'scored' exist only in the first file.